test_data:
  - class: data.secondary_datasets.DarkBenchSneaking
    params:
      n: null
      format_mode: FormatMode.TEST

inference:
  max_new_tokens: 64
  temperature: 0.0
  repetition_penalty: 1.0
  batch_size: 8