# ACE method configuration only: define generation & selection settings.
# This YAML should be merged with a model and concept config to run an experiment.

# First, override the dataset formatting to use CAA templates:
train_data:
  pos:
    params:
      format: SteeringFormat.ARDITI
  neg:
    params:
      format: SteeringFormat.ARDITI
  neutral: null

direction_generation:
  generator:
    class: direction_generation.linear.DiffInMeans
    params: {}
  param_grid:
    # Sweep layers from 25% to 80% of total layers, step size 2
    layer_pct_start: [0.25]
    layer_pct_end:   [0.8]
    layer_step:      [2]
    component:       [null]
    attr:            ['input']
    pos:             [-1]
    # The direction should be unit norm'd. Note this is default. We don't yet have a toggle for on vs. off.
    # get_unit_norm: true

direction_selection:
  class: direction_selection.cosmic.CosmicSelector
  params:
    application_locations: []
    include_generation_loc: true
    generation_pos: ALL
    factors: null
    # Additional params required by COSMIC (same signature as GridSearchSelector)
    result_path: "dim_cosmic_results.csv"
    # COSMIC-specific parameters
    layer_selection_pct: 0.1  # 10% of layers with lowest cosine similarity
    kl_threshold: 0.1         # KL divergence threshold for filtering directions
    negative_applier:
      class: direction_application.unconditional.ActAdd
      params: {}
    negative_application_locations:
      - include_generation_loc: true
        generation_pos: ALL

direction_application:
  class: direction_application.unconditional.DirectionalAblation
  params:
    use_affine: true  # Enable affine transformation for ACE, i.e., adding back a projection of the reference activations.
